name: foshill
description: >
  Easy wardrobe management.

# Prevent accidental publishing to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Localizations
  intl: 0.18.0
  flutter_localizations:
    sdk: flutter

  # BLoC
  flutter_bloc: ^8.1.3

  # Router
  go_router: ^10.0.0

  # Persisting
  drift: 2.9.0
  sqlite3_flutter_libs: 0.5.15

  # Logging
  logging: ^1.2.0

  # Utils
  bloc_concurrency: 0.2.2
  path: ^1.8.2
  path_provider: ^2.0.12

  # Local packages
  database:
    path: packages/database
  extended_image: ^8.0.2

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: 2.4.6
  drift_dev: 2.9.0
  flutter_gen_runner: 5.3.1

  # Lints
  flutter_lints: ^2.0.0

  # Splash & launcher icon
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.0+1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"

flutter_native_splash:
  image: assets/images/splash.png
  color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700

  # Enable generation of localized Strings from arb files.
  generate: true

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 80


