name: foshill
description: >
  Easy wardrobe management.

# Prevent accidental publishing to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Logging
  logging: ^1.2.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


