name: foshill
description: >
  Easy wardrobe management.

# Prevent accidental publishing to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # BLoC
  flutter_bloc: ^8.1.3

  # Persisting
  drift: 2.9.0
  sqlite3_flutter_libs: 0.5.15

  # Logging
  logging: ^1.2.0

  # Utils
  path: ^1.8.2
  path_provider: ^2.0.12


  # Local packages
  database:
    path: packages/database
  extended_image: ^8.0.2

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Codegen
  build_runner: 2.4.6
  drift_dev: 2.9.0

  # Lints
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


