name: database
description: Database-related logic
version: 0.0.1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # Persisting
  drift: 2.9.0
  sqlite3_flutter_libs: 0.5.15

  # Utils
  path: ^1.8.3
  path_provider: ^2.0.15


dev_dependencies:
  # Codegen
  build_runner: ^2.4.5
  drift_dev: 2.9.0

  # Lints
  lints: ^2.0.0

  # Testing
  test: ^1.21.0
